### ISSUE TITLE
Issue with enums

### ISSUE THREAD

**Issue by neovov** [trivago/pbf-loader#5]
When compiling a proto 3 having enums I have the following result:
```js
FooEnum = {
  "FIRST": {
    "value": 0,
    "options": {}
  },
  "SECOND": {
    "value": 1,
    "options": {}
  },
  "THIRD": {
    "value": 2,
    "options": {}
  }
}
```

While I have this using `pbf` in command line:
```js
FooEnum = {
  "FIRST": 0,
  "SECOND": 1,
  "THIRD": 2
}
```

Is this normal?

**Comment by btiwaree** [comment]
Hey @neovov, thanks for creating the issue, I will look into it asap. After a quick glance, i see that _pbf_ in command line uses **resolve-protobuf-schema** to parse protobuf definitions as opposed to **protocol-buffers-schema** that we use here.

**Comment by neovov** [comment]
Gentle ping 😃

**Comment by btiwaree** [comment]
turns out, if I use `protocol-buffers-schema` v2.0.2, I get the:
```
FooEnum = {
  "FIRST": 0,
  "SECOND": 1,
  "THIRD": 2
}
```

However, if I upgrade `protocol-buffers-schema` to latest version, I get:
```
FooEnum = {
  "FIRST": {
    "value": 0,
    "options": {}
  },
  "SECOND": {
    "value": 1,
    "options": {}
  },
  "THIRD": {
    "value": 2,
    "options": {}
  }
}
```

And, since pbf uses `resolve-protobuf-schema` which in turn uses v2.0.2, you are getting the schema without value, options keys. 
Please feel free to report an issue in https://github.com/mafintosh/protocol-buffers-schema
